apiVersion: apps/v1
kind: Deployment
metadata:
    name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: app-container
          image: gcr.io/aesthetic-honor-292122/web:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
